# Generated by Django 4.0.1 on 2022-02-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xevao',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vattudung',
            name='TrangThaiXuat',
            field=models.CharField(choices=[('Đã Xuất', 'Đã Xuất'), ('Chưa Xuất', 'Chưa Xuất')], max_length=50),
        ),
    ]
