# Generated by Django 4.0.1 on 2022-02-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DX', '0002_xevao_status_alter_vattudung_trangthaixuat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vattudung',
            name='TrangThaiKho',
            field=models.CharField(choices=[('Không', 'Không'), ('Có', 'Có')], max_length=50),
        ),
        migrations.AlterField(
            model_name='xevao',
            name='datetimeXera',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
