# Generated by Django 4.0.2 on 2022-02-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DX', '0003_alter_vattudung_trangthaikho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vattudung',
            name='DatetimeXuat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vattudung',
            name='TrangThaiKho',
            field=models.CharField(choices=[('Có', 'Có'), ('Không', 'Không')], max_length=50),
        ),
        migrations.AlterField(
            model_name='xevao',
            name='datetimeXera',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='xevao',
            name='datetimeXevao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
