# Generated by Django 4.0.2 on 2022-02-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DX', '0004_alter_vattudung_datetimexuat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vattudung',
            name='DatetimeXuat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vattudung',
            name='TrangThaiXuat',
            field=models.CharField(choices=[('Chưa Xuất', 'Chưa Xuất'), ('Đã Xuất', 'Đã Xuất')], max_length=50),
        ),
        migrations.AlterField(
            model_name='xevao',
            name='datetimeXera',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='xevao',
            name='datetimeXevao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
