# Generated by Django 4.0.2 on 2022-02-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DX', '0005_alter_vattudung_datetimexuat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vattudung',
            name='DatetimeXuat',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vattudung',
            name='TrangThaiKho',
            field=models.CharField(choices=[('Không', 'Không'), ('Có', 'Có')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vattudung',
            name='TrangThaiXuat',
            field=models.CharField(choices=[('Đã Xuất', 'Đã Xuất'), ('Chưa Xuất', 'Chưa Xuất')], max_length=50),
        ),
        migrations.AlterField(
            model_name='xevao',
            name='datetimeXera',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xevao',
            name='datetimeXevao',
            field=models.DateTimeField(),
        ),
    ]
