# Generated by Django 4.0.2 on 2022-02-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DX', '0006_alter_vattudung_datetimexuat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vattudung',
            name='DatetimeXuat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
