# Generated by Django 4.0.2 on 2022-02-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DX', '0007_alter_vattudung_datetimexuat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vattudung',
            name='TrangThaiXuat',
            field=models.CharField(choices=[('Chưa Xuất', 'Chưa Xuất'), ('Đã Xuất', 'Đã Xuất')], max_length=50),
        ),
    ]
